# Generated by Django 5.0.9 on 2024-09-18 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogpages', '0002_blogpagetags_blogdetail_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogdetail',
            name='body',
        ),
    ]
