# Generated by Django 5.0.9 on 2024-09-20 00:53

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogpages', '0004_blogdetail_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogdetail',
            name='body',
            field=wagtail.fields.StreamField([('image', 0), ('doc', 1), ('page', 2)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 1: ('wagtail.documents.blocks.DocumentChooserBlock', (), {}), 2: ('wagtail.blocks.PageChooserBlock', (), {'page_type': ['blogpages.BlogDetail'], 'required': False})}, null=True),
        ),
    ]
