# Generated by Django 5.0.9 on 2024-09-22 19:38

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogpages', '0006_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogdetail',
            name='body',
            field=wagtail.fields.StreamField([('text', 0), ('info_block', 1), ('faq_block', 4), ('image', 5), ('doc', 6), ('page', 7), ('author', 8), ('call_to_action', 11)], blank=True, block_lookup={0: ('wagtail.blocks.TextBlock', (), {}), 1: ('blocks.blocks.InfoBlock', (), {}), 2: ('wagtail.blocks.CharBlock', (), {'required': True}), 3: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link'], 'required': True}), 4: ('wagtail.blocks.StructBlock', [[('question', 2), ('answer', 3)]], {}), 5: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 6: ('wagtail.documents.blocks.DocumentChooserBlock', (), {}), 7: ('wagtail.blocks.PageChooserBlock', (), {'page_type': ['blogpages.BlogDetail'], 'required': False}), 8: ('wagtail.snippets.blocks.SnippetChooserBlock', ('blogpages.Author',), {}), 9: ('wagtail.blocks.PageChooserBlock', (), {}), 10: ('wagtail.blocks.CharBlock', (), {'max_length': 100, 'required': False}), 11: ('wagtail.blocks.StructBlock', [[('text', 3), ('page', 9), ('button_text', 10)]], {'label': 'CTA #1'})}, null=True),
        ),
    ]
